apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: copy-pipeline
spec:
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: ""
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
  results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.oci-copy.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.oci-copy.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:4f660cb54aa6b125a799d8999ec293a5e783da8c3b4c2d6246e78c0d08b6a56b
          - name: kind
            value: task
        resolver: bundles
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - init
      taskRef:
        params:
          - name: name
            value: git-clone
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:fedaacbf05ff7b2cdd36bff6cb1f103755cb5dc0b4adc0540136d3606ade18a5
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: oci-copy
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: OCI_COPY_FILE
          value: $(params.oci_copy_file)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - clone-repository
      taskRef:
        params:
          - name: name
            value: oci-copy
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-oci-copy:0.1@sha256:acef9b7d66798f16d2a2eaddeea3a9abdedc6e2503b12dc16fe839a492a5eb69
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: source
          workspace: workspace
    - name: apply-tags
      params:
        - name: IMAGE
          value: $(tasks.oci-copy.results.IMAGE_URL)
      runAfter:
        - oci-copy
      taskRef:
        params:
          - name: name
            value: apply-tags
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:c5ed9ff3865b8805e6e17c0fd4fb601f92cafa2c6c11ee87e72884ee58088ac9
          - name: kind
            value: task
        resolver: bundles
  workspaces:
    - name: workspace
    - name: git-auth
      optional: true
